import { Bricolage_Grotesque } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

// Load only Bricolage Grotesque font with CSS variable
const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bricolage',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${bricolage.variable}  font-sans antialiased bg-white min-h-screen h-full w-full`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
